### ISSUE TITLE
Cannot specify cert file

### ISSUE THREAD

**Issue by zentale** [Jmainguy/kibanaRefreshFields#1]
When running `kibanaRefreshFields` I get `_score: x509: certificate signed by unknown authority` error.
it would be nice to be able to specify a crt file - that the client should use.

**Comment by Jmainguy** [comment]
Hey @zentale,

This is a great idea, sorry for taking so long to get to this. I believe https://github.com/Jmainguy/kibanaRefreshFields/pull/2 should add this feature. Let me know if this works for you or not.

**Comment by zentale** [comment]
Thanks, that's it. Will try it out later, closing the issue.
